version: '3.3'
services:
  frontend:
    build:
      context: frontend
      args:
        - node_env=development
    ports:
      - "9000:9000"
    command: 
      - node_modules/grunt-cli/bin/grunt
      - serve
    volumes:
      - ./frontend/app:/home/app
  api:
    build:
      context: .
      args:
        - node_env=development
    environment:
      - MONGOLAB_URI=mongodb://mongo:27017/nadeefiler
      - CLOUDAMQP_URL=amqp://rabbitmq
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    ports:
      - "1337:1337"
    entrypoint:
      - ./script/wait-for-services.sh
    command: 
      - npm
      - start
    depends_on:
      - mongo
      - rabbitmq
      - redis
  profilers:
    build:
      context: profilers
      args:
        - node_env=development
    environment:
      - MONGOLAB_URI=mongodb://mongo:27017/nadeefiler
      - CLOUDAMQP_URL=amqp://rabbitmq
    entrypoint:
      - ./script/wait-for-services.sh
    command:
      - npm
      - start
    depends_on:
      - mongo
      - rabbitmq
  mongo:
    image: mongo:latest
  rabbitmq:
    image: rabbitmq:latest
  redis:
    image: redis:latest
